version: "3"
services:
  rt999web:
    container_name: rt999web
    image: "ng999:web"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9032:5000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
