version: "3"
services:
  rtapinginx:
    container_name: ng999_web
    image: "ng999:web"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9032:80"
    networks:
      - internal

networks:
  internal:
    driver: bridge
